iq_text_generator.text_generator.*:
  type: config_entity
  label: 'Text Generator settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin_id:
      type: string
      label: 'Plugin ID'
    settings:
      type: mapping
      label: 'Settings'
